apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-backend/deployment.yaml
  - 01-backend/service.yaml
  - 02-frontend/deployment.yaml
  - 02-frontend/service.yaml
  - 03-redis/deployment.yaml
  - 03-redis/service.yaml
  - 04-postgres/deployment.yaml
  - 04-postgres/service.yaml
