---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gmail-credentials
  namespace: dev
spec:
  encryptedData:
    GMAIL_APP_PASSWORD: AgB24JB2+AeANWOK524Kl6Zxszo52dXVSe53pb7F0Ck7I/v/L8JhXP4ymk6AQBU+ADmHvk6wLFCDft7di0rYSyjV05jX4kjFbR7PhT51c4MFDqQLLz6LQ3FiaHxCAfsRoEFF21J5yvhJpEBs7qR+fUpmUO4MllodXfOlgTHBaJ1pQmmC/r3PwlNPQyyWN+YCCEKWPqB3lOpUkGFaR+5NBa6qSzmYpiLCQaBRjiUHb+62PWNXn2gl7F9hZw4y1q0keNW+EyId1KvfsqQf5yHgJGC9HhiqURKgMH43GNQnDcsdpiIvso8Pq+qOZnKwAxzKZH3QYx8/yKVvULJIF4W8WzNbewUwoDbzzIqvqNkzuKnVPSv8Sc7+TzTjRvAH1v9uXni9qJEkGjxsbYu9JrsV98wCYPKPf5ZxTBUMQps5vIQG0mSt5I3k24mD8qG57me4AVk64Ocl58zmmbWfyfJRP8ZX/Tg3lMo2spUHVsliVaOn6jUasRQFtg4x2tjwGuz6Sd6v5eIqTOao3PGTo3xbXBR9RRxEZN/3Xik7t278jzMNH6RPv/BFD8jjYnU7pgIe646ZyjiVYUK7YBTXaRtytK18vVupfZO+dhsGsGjgpA9U/tYBCNlQ07UYcIAObAN2XU7kw4QLJ/vqxUFzA2Y7VKAJLXiJKcjo1T1xV8KCCIaHzX+PMnCloF+fo0juRGfQd0Np1nryHBhOdLMZ6+bf7Khw
    GMAIL_USERNAME: AgBNCCwCie7E4oTzzEWOGohNhjikdLwehzlFzmbsDiK3WNO/Aot/3ZEWQ1rrO0DeN51Tz0P1x4x+ZrclH8xht9ZD+rl6iSDK6YchPovyf9VYQSNBJc4iXCRhK3eJz2F2fnfkH9jaAafxJ6zfVPZHyU6jS4NjaXY7RgyD3+hD/qRbORcs72yAr+NJ3ZGzAE6ri7wXXw4NMY4iBHicrxodXx2FhNEdbb/AgsmuLSuDOWELz5NA5CH6GWhFEV98sPhX+caiRYPKwu4vSynbqbPJz412eCu9k5wbjgCpbxuqsIinnWST87jho32zRzwV2+POAhVgxAERZJsxMacczM5nr/15FkKcGw1WHzil/66xNJimju/W4QKdBkQX8ikskuUNdEzdK8c3zzE/rS5e9VQd16W4QVyZem5OEUxAXJRZ2vZBafLRaevbATYf1YFsdieMNb3a5pD0IeyB99T7hez26wccjzoF+WyUQCa7UpsYpaG5JRUg3j7es7/tgK+XQdi1z7L/xBYxWSG2Qw4M7O2As6OQSona+02VjHkV4OsYCAFCD5asrKG9/CWsfz9ADkOKYX2LMymviJzreKzCDcMvPmKUNcX+KE0bYIMXfqe5gQj3XQGs8hkQgdcJdIqGTAdn/ty6zPI5NkoJqO2zTE3jXGr/YB46yYNtMhgjlsuAPr8OdyHzO+XH8DcMi51r/FCX5gXbP3TuhwMx4D9WqZcomrK/G4g=
  template:
    metadata:
      name: gmail-credentials
      namespace: dev
