apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/1ik/cloud-native-app-demo-workflow
    targetRevision: HEAD
    path: infrastructure/k8s/03-redis

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
