apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../01-backend
  - ../../02-frontend
  - ../../03-redis
  - ../../04-postgres

labels:
  - includeSelectors: true
    pairs:
      env: staging

patches:
  - path: backend-patch.yaml
